language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
      env: coverage=1 lint=1
    - php: '7.2'
      env: deps='low'
    - php: 7.3
    - php: 7.4snapshot

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-6.5.phar
  - if [[ $coverage = 1 ]]; then mkdir -p build/logs; fi
  - if [[ $coverage = 1 ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v2.0.0/php-coveralls.phar; fi
  - if [[ $lint = 1 ]]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.10.0/php-cs-fixer.phar; fi
  - if [[ $lint = 1 ]]; then composer global require --dev 'phpstan/phpstan:^0.10'; fi
  - wget -O box.phar https://github.com/humbug/box/releases/download/3.2.0/box.phar
  - export BOX_BIN=$(pwd)/box.phar

install:
  - if [[ $coverage = 1 ]]; then composer require --dev --no-update 'phpunit/php-code-coverage:^5.3'; fi
  - if [[ ! $deps ]]; then composer install --prefer-dist --no-progress --no-suggest --ansi; fi
  - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
  - if [[ $coverage = 1 ]]; then phpdbg -qrr phpunit.phar --coverage-clover build/logs/clover.xml; else php phpunit.phar; fi
  - if [[ $lint = 1 ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
  - if [[ $lint = 1 ]]; then phpstan analyse -l5 --ansi src; fi
  - if [[ ! $deps && $TRAVIS_PHP_VERSION = "7.2" ]]; then ./bin/compile; fi

after_success:
  - if [[ $coverage = 1 ]]; then travis_retry php php-coveralls.phar; fi

deploy:
  provider: releases
  api_key:
    secure: Oq9TAPQZqnjxhbprWZQE64GhK4vxBHjvcMkS9dkbkCJQVz8cSqGxZOFqMOHulraFs2IX9PLeplrZReFMT630KkMNf74mkTtL9WMuaMJV0bbUPY+X7YpDGlLNNU7OA9Rxjr3y68x1jVxD6mLSlCFZP00qvmYRlOE1i2ltjO7L5Sw=
  file: schema.phar
  skip_cleanup: true
  on:
    tags: true
    repo: api-platform/schema-generator
    php:  '7.2'
    condition: "! $deps"
